### ISSUE TITLE
Json mask adding extra fields to the output while using * in the fields filter

### ISSUE THREAD

**Issue by anshulongithub** [nemtsov/json-mask#12]
"MyFileAttribute": [ {"attrib0": "eljeelj",
          "attrib1": "qer",
          "attrib2": DB",
          "attrib3": "some Val",
          "file": "some Val",
          "size": 347,
          "Platform": "some plateform"
}]
for the above json array when we use * in the fields filter we get 
"MyFileAttribute": [
      {
        "__cachedRelations": {},
        "__data": {
          "attrib0": "eljeelj",
          "attrib1": "qer",
          "attrib2": DB",
          "attrib3": "some Val",
          "file": "some Val",
          "size": 347,
          "Platform": "some plateform",
          
        }
      }
While filtering using * it is adding  "__cachedRelations": {}, and copying the filtered fields within the __data field attribute.

**Comment by nemtsov** [comment]
Since `json-mask` doesn't have `__cachedRelations` in its code, my hunch is that the object you're providing to it has that as a property. But it's difficult to tell without an example I can execute. Can you please provide an example I can run?

**Comment by anshulongithub** [comment]
That's right, my object had those fields in it, after filtering those fields before feeding the filtered object to json-mask api, the * wild card is working as expected. Thanks!
