### ISSUE TITLE
Incorrect masking

### ISSUE THREAD

**Issue by kk-android** [nemtsov/json-mask#15]
```
var mask = require('json-mask');

var originalObj = {
  id: 'z12gtjhq3qn2xxl2o224exwiqruvtda0i',
  url: 'https://plus.google.com/102817283354809142195/posts/F97fqZwJESL',
  object: {
    objectType: 'note',
    content: 'A picture... of a space ship... launched from earth 40 years ago.',
    attachments: [{
      objectType: 'image',
      url: 'http://apod.nasa.gov/apod/ap110908.html',
      image: {height: 284, width: 506}
    }]
  },
  provider: {title: 'Google+'}
};

var fields = '*/content';

var masked_data = mask(originalObj, fields);

console.log(JSON.stringify(masked_data));

```
Output:

{"object":{"content":"A picture... of a space ship... launched from earth 40 years ago."},"provider":{}}

The key "provider" should not be present in the output.

**Comment by nemtsov** [comment]
@kk-android Although in your case, you may not want the other property, consider the case where a service returns an object with a `provider` that may conditionally have the property `content` and in the client code, you have `if (object.content) {}; if (provider.content) {}`. In that case, if `json-mask` removes the object `provider` an error would be thrown. So, `json-mask` intentionally keeps object structure in this case to avoid `TypeError: Cannot read property '<NAME>' of undefined` errors.
