### ISSUE TITLE
How to get keys that contains ",/()"?

### ISSUE THREAD

**Issue by mochja** [nemtsov/json-mask#164]
```json
{"foo/bar": 1,"private":"true"}
```

How can mask this json object so that private is not shown?

**Expected output**

```json
{"foo/bar": 1}
```

**Comment by nemtsov** [comment]
Unfortunately, you can't right now. That said, a PR to add support for handling these keys (with terminals in them) is very much welcome.

**Comment by nemtsov** [comment]
@mochja this has been published in v2.0.0 (https://github.com/nemtsov/json-mask/releases/tag/v2.0.0)
Thank you for contributing the fix for this issue!
