### ISSUE TITLE
Getting params from a nested JSON without grouping the params

### ISSUE THREAD

**Issue by ashwinnatty** [nemtsov/json-mask#17]
Lets say we have a JSON like below and I want to grab the language and experience under skills.
{
	"name": "john",
	"age": "30",
	"skills": [{
			"language": "Java",
			"experience": "5"
		},
		{
			"language": "CSharp",
			"experience": "10"
		}
	]
}

If I group thee fields i request together like below i seem to be getting both language and experience 
var fields = 'skills(experience,language)';

**Response**
{"skills":[{"experience":"5","language":"Java"},{"experience":"10","language":"C
Sharp"}]}

But If I don't group the fields and request them individually like below I only seem to get only the last requested parameter (in this case language). Ideally I should have got both experience and language

var fields = 'skills(experience),skills(language)';

**Response**
{"skills":[{"language":"Java"},{"language":"CSharp"}]}
 
Kindly take a look

**Comment by wmakeev** [comment]
**json-mask** don't correct process this style of syntax. I fix it in [my fork](https://github.com/wmakeev/json-mask/commits/issue-16). I will make pull request for this.

**Comment by nemtsov** [comment]
Hey there. The query for what you want to filter would be `skills(experience,language)`. The parser isn't intelligent enough to collapse the two `skills` keys into one (I'm not certain it should either, tbh). This is the equivalent of creating the following object:

```
{
  skills: {
    properties: ['experience']
  },
  skills: {
    properties: ['language']
  }
}
```

On one hand, one can argue that JS should be intelligent enough to combine these two, on the other it may make sense for the second `skills` in the object above to override the first. `json-mask` takes the latter approach.
