### ISSUE TITLE
An Empty First param followed by a Valid param gives back empty response

### ISSUE THREAD

**Issue by ashwinnatty** [nemtsov/json-mask#18]
Say I have a JSON like below
{
	"name": "john",
	"age": "30",
	"skills": [{
			"language": "Java",
			"experience": "5"
		},
		{
			"language": "CSharp",
			"experience": "10"
		}
	]
}

When I try to ask for a field followed by an empty string like below i get response 
 'name,' 

**Response**
{"name":"john"}

But when i have a empty string followed by a field that i want to grab i get an empty response.
Ideally we would have expected a response similar to above scenario

**Response**
{}

Kindly check.

**Comment by wmakeev** [comment]
I think masks like `,name` and `name,` is incorrect and should raise error like in [google api](https://developers.google.com/+/web/api/rest/latest/activities/list) - `"Invalid field selection ,items"`. **json-mask** have very limited syntax error check.

**Comment by nemtsov** [comment]
Apologies for the delayed response @ashwinnatty. `json-mask` doesn't currently support that syntax in its grammar:

```
 *  Grammar:
 *     Props ::= Prop | Prop "," Props
 *      Prop ::= Object | Array
 *    Object ::= NAME | NAME "/" Object
 *     Array ::= NAME "(" Props ")"
 *      NAME ::= ? all visible characters ?
 *
```

Whether it should or should't throw a syntax error is debatable. I think I'm leaning toward the former now, but when I wrote it a few years ago I wasn't interested in the compiler ever throwing errors.
