### ISSUE TITLE
Nested arrays masking?

### ISSUE THREAD

**Issue by wmakeev** [nemtsov/json-mask#19]
@nemtsov what do you think about nested arrays masking?

I trying to fix some issues in current version of json-mask and faced with this question. I can't find example for similar behaviour in google API.

**Example:**

```js
let obj = {
  a: [
    { b: 0 },
    [{ b: 1 }],
    [[{ b: 2 }]],
    [[[{ b: 3 }]]]
  ]
}
```

**Mask:** `a/b`

**Result** (should json-mask fall in to nested arrays in the masking process?):

```js
{
  a: [
    { b: 0 },
    [{ b: 1 }],
    [[{ b: 2 }]],
    [[[{ b: 3 }]]]
  ]
}
```

**Comment by nemtsov** [comment]
Apologies for the very late response. I believe 'a/b' should return `a: [{ b: 0 }, [], []]` and `a/*/b` should respond with the latter.
