### ISSUE TITLE
Mask, not filter data?

### ISSUE THREAD

**Issue by m0hdasif** [nemtsov/json-mask#54]
@nemtsov,

Is there any way to provide options to get masked data instead of filtered data?

**inputObject**
```js
{ 
 a: 'xyz@xyz.com', 
 b:'some data'
}
```
**expectedResult**
```js
{
  a:'xyz@xyz.com',
  b:'xxxxx'    
}
```

**Current functionality** 
```js
mask(inputObject, 'a');
```
  **output**
```js
{
  a:'xyz@xyz.com'
}
```

**Comment by nemtsov** [comment]
@m0hdasif The purpose of this library is slightly different. It would be pretty neat to do though, just not as part of json-mask. I see how the name is causing the confusion though.
