### ISSUE TITLE
JsonMask '*' not returning 0 values

### ISSUE THREAD

**Issue by tectual** [nemtsov/json-mask#7]
Thanks for your awesome plugin! Which i have used heavily in my app and node/hapi plugins. One problem that I noticed is '*' doesn't return all values. 
```
JsonMask = require 'json-mask'
JsonMask { id:1, name: 'Bar 100', hits:0 }, '*'    # => { id: 1, name: 'Bar 100' } missing hits as it's 0
JsonMask { id:1, name: 'Bar 100', hits:0 }, 'hits'   # => { hits: 0 }
```
Here is my (odme)[https://github.com/tectual/odme] as a real life example, where you can see (here)[https://github.com/tectual/odme/blob/master/src/base.coffee] at line 151 the **mask** method is trying to get all attributes. But it fails.

**Comment by nemtsov** [comment]
@tectual thanks for the heads up! That was a bug. It's resolved in *v0.3.3*.
